version: '3.4'

services:
  versionpe:
    image: versionpe
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      - NODE_ENV = production
      - DB_URL = mongodb://mongo
    ports:
      - 3000:3000
    networks:
      - bizos
  mongo:
    image: mongo:6
    ports:
      - "3001:27017"
    volumes:
      - ./database:/data/bizos
    networks:

      - bizos
   
volumes:
  database:
networks:
  bizos:
